[global]
  hist: /partyhome/hist       # put db/thumbs/etc. here by default

[accounts]
  u1: p1
  u2: p2
  u3: p3

[/Truenas]
  /truenas
  accs:
    r: *                      # read only for everyone

[/Party]
  /partyhome/files
  accs:
    rw: u3                    # u3 can read/write

